spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accounts?createDatabaseIfNotExist=true
    username: root
    password: root
  application:
    name: order-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

